version: '3.3'
services:

  wordpress:
    depends_on:
      - db
    image: wordpress:4.9
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      DEMO_THING: "Pretty nifty"
    logging:
      driver: splunk
      options:
        splunk-format: "json"
        splunk-insecureskipverify: "true"
        splunk-source: "app"
        splunk-token: "37a1d361-2114-400b-a0c7-3c84ddd3074d"
        splunk-url: "https://prd-p-s74ir.splunkcloud.com:8088"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    logging:
      driver: splunk
      options:
        splunk-format: "json"
        splunk-insecureskipverify: "true"
        splunk-source: "app"
        splunk-token: "37a1d361-2114-400b-a0c7-3c84ddd3074d"
        splunk-url: "https://prd-p-s74ir.splunkcloud.com:8088"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
    volumes:
      - type: bind
        source: /mnt/sql
        target: /var/lib/mysql

volumes:
  wordpress:
  db:
