---
  - name: InstallDocker
    hosts: all
    become: yes
    become_user: root
    tasks:
      - name: Add Docker GPG apt Key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
      - name: Add Docker Repository
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu focal stable
          state: present
      - name: Update apt and install docker-ce
        apt:
          name: docker-ce
          state: latest
          update_cache: true
      - name: Install docker-compose
        apt:
          name: docker-compose
          state: latest
      - name: formatting the volume
        filesystem:
          dev: "/dev/xvdn"
          fstype: "ext4" #ext4, ext3 etc
      - name: mounting the filesystem
        mount:
          name: "/mnt"
          src: "/dev/xvdn"
          fstype: "ext4" #ext4, ext3 etc
          state: mounted
      - name: Copy the Splunk Forwarder Debian archive file to remote servers.
        copy:
           src: ./splunkforwarder-8.2.7-2e1fca123028-linux-2.6-amd64.deb
           dest: /home/ansible/
           owner: ubuntu
           group: ubuntu
           mode: 0644
      - name: Install pexpect
        apt:
          name:
            - python-pexpect
          state: present
      - name: Install Splunk Forwarder Debian archive file to remote servers.
        apt: deb=/home/ansible/splunkforwarder-8.2.7-2e1fca123028-linux-2.6-amd64.deb
      - name: Install Splunk forwarding app - splunkclouduf.spl
        unarchive:
          src: ./splunkclouduf.spl
          dest: /opt/splunkforwarder/etc/apps/
      - name: Copy the Splunk Forwarder config from your centralized server to remote servers.
        copy:
          src: ./inputs.conf
          dest: /opt/splunkforwarder/etc/system/local/
          owner: splunk
          group: splunk
          mode: 0600
      - name: Stop Splunk service
        remote_user: ubuntu
        become: yes
        become_method: sudo
        become_user: root
        command: /opt/splunkforwarder/bin/splunk stop
      - name: Start Splunk forwarder service.
        remote_user: ubuntu
        become: yes
        become_method: sudo
        become_user: root
        expect:
          command: /opt/splunkforwarder/bin/splunk start --accept-license
          timeout: 60
          responses:
             (.*)Please enter an administrator username(.*): "admin"
             (.*)Please enter a new password(.*): "redhat@1020"
             (.*)Please confirm new password(.*): "redhat@1020"
      - name: Check Splunk forwarder service.
        command:
          /opt/splunkforwarder/bin/splunk status
        register: service_splunk_status
      - name: Report Splunk forwarder Status.
        debug:
           var: service_splunk_status.stdout_lines

